version: '3.9'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env

  nginx:
    build:
      context: .               # Use project root as build context
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
